### ISSUE TITLE
Manage time dimension

### ISSUE THREAD

**Issue by FrancoisPgm** [brainhack-school2020/3D_fMRI_visualization#3]

**Comment by lunebellec** [comment]
alright, so is the closing of this issue means you are done implementing the dynamic visualization ??

**Comment by FrancoisPgm** [comment]
Yes, I am able to plot different time points, changing them with a slider, but now I want to implement the plotly built-in slider that comes with play/pause buttons (i.e. ([https://plotly.com/javascript/gapminder-example/](https://plotly.com/javascript/gapminder-example/)).)
